name: ibraheem_portfolio
description: A professional portfolio website

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.11
  google_fonts: ^6.1.0
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.1+1
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/